# Generated by Django 5.0.6 on 2024-05-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bestseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('cover', models.TextField()),
                ('isbn', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='New_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('cover', models.TextField()),
                ('isbn', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
