# Generated by Django 5.0.6 on 2024-05-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
